@url = http://localhost:8080/api/v1/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGMyNmE3MTUzMjdkZDY4MTc5NGEyZSIsImVtYWlsIjoiYXNkQGFzZC5jb20iLCJ1c2VybmFtZSI6ImVsam9lMTgyIiwiaWF0IjoxNjUzMzUyMzQ5LCJleHAiOjE2NTM0Mzg3NDl9.74J6QFgnZGZY_o3eJIzsWURhu7RDAYZzJwqZzeJc-Bs

###
POST {{url}}/signup HTTP/1.1
Content-Type: application/json

{
  "username": "eljoe182",
  "email": "asd@asd.com",
  "password": "asd"
}

###
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "asd@asd.com",
  "password": "asd123"
}

###
POST {{url}}/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": "asd@asd.com"
}

###
POST {{url}}/reset-password HTTP/1.1
Content-Type: application/json

{
  "token": "okjt0kyiw4d02d6a0sk4azf",
  "password": "asd123"
}

###
GET {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
@id = 62854cff184816dc42cd26bf
PUT {{url}}/update/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Joe mod",
  "email": "asd@asd.com",
  "phone": "1234567890"
}

###
@id = 62854cff184816dc42cd26bf
POST {{url}}/change_password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "asd",
  "newPassword": "asd123"
}