@url = http://localhost:4000/api/v1/purchase
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGMyNmE3MTUzMjdkZDY4MTc5NGEyZSIsImVtYWlsIjoiYXNkQGFzZC5jb20iLCJ1c2VybmFtZSI6ImVsam9lMTgyIiwiaWF0IjoxNjU0MjI5MzQ0LCJleHAiOjE2NTQzMTU3NDR9.X8FdI4o33ahD6ZLH1jD4svnyobckYJlV1_usWdAjPvk

###
GET {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{url}}/store HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "commerceId": "new-94708",
  "commerceDescription": "TOTTUS",
  "walletId": "629678078780c63d2722f74a",
  "walletDescription": "Wallet 1",
  "dateInvoice": "2022-06-03",
  "description": "Test",
  "subTotal": 800,
  "discountTotal": 0,
  "net": 800,
  "tax": 152,
  "total": 952,
  "items": [
    {
      "productId": "new-36799",
      "description": "AGUA",
      "quantity": 1,
      "price": 800,
      "discount": 0,
      "total": 800
    }
  ]
}